package szoftprojlab;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Asteroid.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//


import szoftprojlab.entity.Entity;
import szoftprojlab.resource.Resource;
import szoftprojlab.resource.ResourceNames;
import szoftprojlab.resource.ResourceStorage;

import java.util.List;

public class Asteroid implements Steppable, ResourceStorage {
	private int idx;
	private int layers;
	private boolean isEmpty;
	private boolean nearSun;
	private Resource resource;
	private List<Asteroid> neighbors;
	private List<Entity> entities;
	private List<TeleportGate> gates;

	public void SunStorm() {
	}
	
	public void ChangeNearSun() {
	}
	
	public void Explode() {
	}
	
	public void Drill() {
	}
	
	public void Accept(Entity entity) {
	}
	
	public void Remove(Entity entity) {
	}
	
	public void Mine(ResourceStorage rs) {
	}
	
	public void Place(Resource resource) {
	}
	
	public Asteroid GetNeighbor(int idx) {
		return null;
	}
	
	public TeleportGate GetTeleportGate(int idx) {
		return null;
	}
	
	public void AddResource(ResourceNames name, Resource resource) {
	}
	
	public void AddEntitysResourcesToComparator() {
	}
	
	public void DestroyResource() {
	}
	
	public void PlaceTeleportGate(TeleportGate gate) {
	}

	public void Step() {

	}
}
