package szoftprojlab;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Entity.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//




public abstract class Entity implements Steppable {
	private Asteroid asteroid;
	public void SunStorm() {
	}
	
	public void Explode() {
	}
	
	protected void Move(Asteroid asteroid) {
	}
	
	protected void Drill() {
	}
	
	protected void Teleport(TeleportGate gate) {
	}
	
	protected void AddResourcesToComparator() {
	}
}
