package szoftprojlab;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//


import szoftprojlab.entity.Player;
import szoftprojlab.resource.Resource;
import szoftprojlab.resource.ResourceNames;

import java.util.List;
import java.util.Scanner;

public class Game {
    private static Game singleClassInstance = null;

    private Sun sun;
    private List<Player> players;

    public void StartGame() {
        System.out.println("Game.StartGame()");

        sun = Sun.getInstance();
        Asteroid a1 = new Asteroid(0, 1);
        Asteroid a2 = new Asteroid(1, 1);
        a1.AddNeighbor(a2);
        Player player = new Player();


        System.out.println("return from Game.StartGame()");
    }

    public void AddResource(ResourceNames name, Resource resource) {
    }

    public void ClearResources() {
        System.out.println("Game.ClearResources()");
        System.out.println("return from Game.ClearResources()");
    }

    public void PlayerDie(Player player) {
        System.out.println("Game.PlayerDie()");

        System.out.print("Is the playercount greater than 1? (Y|N) ");
        Scanner scanner = new Scanner(System.in);
        String input = scanner.next();

        if (!input.equalsIgnoreCase("Y")) {
            EndGame();
        }

        System.out.println("return from Game.PlayerDie()");
    }

    public void AddPlayer(Player player) {
        if (!players.contains(player))
            players.add(player);
    }

    public void EndGame() {
        System.out.println("Game.EndGame()");
        System.out.println("return from Game.EndGame()");
    }

    public void AddToOwner(Resource resource) {
        System.out.println("Game.AddToOwner()");
        System.out.println("return from Game.AddToOwner()");
    }

    public void CheckForVictory() {
        System.out.println("Game.CheckForVictory()");
        System.out.println("return from Game.CheckForVictory()");
    }

    public static Game getInstance() {
        if (singleClassInstance == null)
            singleClassInstance = new Game();

        return singleClassInstance;
    }
}
