package szoftprojlab;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ice.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//




public class Ice implements Resource {
	public void SeeSun(Asteroid asteroid) {

	}

	public void AddToOwner(ResourceStorage rs) {
	}
}
