package szoftprojlab;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Iron.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//




public class Iron implements Resource {
	public void SeeSun(Asteroid asteroid) {
	}
	
	public void AddToOwner(ResourceStorage rs) {
	}
}
