package szoftprojlab;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//




public class Player extends Entity implements ResourceStorage {
	private TeleportGate gates;
	private Resource inventory;
	public void Step() {
	}
	
	private void Mine() {
	}
	
	private void PlaceResource(Resource resource) {
	}
	
	private void PlaceGate(Asteroid asteroid) {
	}
	
	private void MakeGate() {
	}
	
	private void MakeAndPlaceRobot() {
	}
	
	public void AddResource(ResourceNames name, Resource resource) {
	}
	
	protected void AddResourcesToComparator() {
	}
}
