package szoftprojlab;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Resource.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//


public interface Resource {
    public void SeeSun(Asteroid asteroid);

    public void AddToOwner(ResourceStorage rs);
}
