package szoftprojlab;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Robot.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//




public class Robot extends Entity {
	public void Step() {
	}
	
	public void Explode() {
	}
	
	public void Robot(Asteroid asteroid) {
	}
}
