package szoftprojlab;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Steppable.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//




public interface Steppable {
	public void Step();
}
