package szoftprojlab;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Steppable.java
//  @ Date : 10/03/2021
//  @ Author : 
//
//




public interface Steppable {
	/**
	 * The steppable steps one in the round
	 */
	public void Step();
}
