package szoftprojlab;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sun.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//




public class Sun implements Steppable {
	private static Sun singleClassIntance = null;

	private int counter;
	private int cycle;
	private Asteroid asteroids;
	public void Step() {
	}
	
	private void SunStorm() {
	}
	
	private void ChangeNearSun() {
	}

	public static Sun getInstance() {
		if (singleClassIntance == null)
			singleClassIntance = new Sun();

		return singleClassIntance;
	}
}
