package szoftprojlab;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sun.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//


import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Sun implements Steppable {
	private static Sun singleClassIntance = null;

	private int counter;
	private int cycle;
	private double sunStormProbability;
	private int nextSunStormIn;
	private List<Asteroid> asteroids = new ArrayList<>();

	public void Init(int nearSunCycle, double _sunStormProbability) {
		cycle = nearSunCycle;
		sunStormProbability = _sunStormProbability;
		nextSunStormIn = (int) (1 / sunStormProbability);
	}

	public void ClearAsteroids() {
		asteroids.clear();
	}

	public void Step() {
		System.out.println("Sun.Step()");

		System.out.print("Do you want to call ChangeNearSun()? (Y|N) ");
		Scanner scanner = new Scanner(System.in);
		String input = scanner.next();

		if (input.equalsIgnoreCase("Y")) {
			ChangeNearSun();
		}


		System.out.print("Do you want to call SunStorm()? (Y|N) ");
		input = scanner.next();

		if (input.equalsIgnoreCase("Y")) {
			SunStorm();
		}

		System.out.println("return from Sun.Step()");
	}
	
	private void SunStorm() {
		System.out.println("Sun.SunStorm()");

		System.out.println(asteroids.size());

		asteroids.forEach(Asteroid::SunStorm);

		System.out.println("return from Sun.SunStorm()");
	}
	
	private void ChangeNearSun() {
		System.out.println("Sun.ChangeNearSun()");
		asteroids.forEach(Asteroid::ChangeNearSun);
		System.out.println("return from Sun.ChangeNearSun()");
	}

	public void AddAsteroid(Asteroid asteroid) {
		System.out.println("Sun.AddAsteroid()");

		if (!asteroids.contains(asteroid))
			asteroids.add(asteroid);

		System.out.println("return from Sun.AddAsteroid()");
	}

	public static Sun getInstance() {
		if (singleClassIntance == null) {
			System.out.println("Sun - create");
			singleClassIntance = new Sun();
			System.out.println("return from Sun - create");
		}

		return singleClassIntance;
	}
}
