package szoftprojlab;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TeleportGate.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//


import szoftprojlab.resource.*;

import java.util.List;

public class TeleportGate {
	private int idx;
	private TeleportGate pair;
	private Asteroid asteroid;
	private static Blueprint teleportgateBlueprint = new Blueprint(new Iron(), new Iron(), new Ice(), new Uranium());

	public TeleportGate(int ID) {
		idx = ID;
	}

	public Asteroid GetPairAsteroid() {
		return pair.asteroid;
	}
	
	public void Place(Asteroid asteroid) {
		this.asteroid = asteroid;
	}
	
	public void SetPair(TeleportGate gate) {
		pair = gate;
		if (!gate.HasPair())
			gate.SetPair(this);
	}

	public Boolean HasPair() {
		return pair != null;
	}

	public static List<Resource> CanCraft(List<Resource> rs) {
		List<Resource> list = teleportgateBlueprint.IsCraftable(rs);
		return list;
	}

	public int GetId() {
		return idx;
	}
}
