package szoftprojlab;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TeleportGate.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//




public class TeleportGate {
	private int idx;
	private TeleportGate pair;
	private Asteroid asteroid;
	public Asteroid GetPairAsteroid() {
		return null;
	}
	
	public void Place(Asteroid asteroid) {
	}
	
	public void SetPair(TeleportGate gate) {
	}
}
