package szoftprojlab;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Timer.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//




public class Timer {
	private static Timer singleClassIntance = null;

	public void Tick() {
	}

	public static Timer getInstance() {
		if (singleClassIntance == null)
			singleClassIntance = new Timer();

		return singleClassIntance;
	}
}
