package szoftprojlab.resource;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Coal.java
//  @ Date : 10/03/2021
//  @ Author : 
//
//


public class Coal extends Resource {
    @Override
    public void AddToOwner(ResourceStorage rs) {
        System.out.println("Coal.AddToOwner()");
        rs.AddResource(ResourceNames.Coal, this);
        System.out.println("return from Coal.AddToOwner()");
    }
}
