package szoftprojlab.resource;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Coal.java
//  @ Date : 10/03/2021
//  @ Author : 
//
//


public class Coal extends Resource {
    @Override
    public boolean equals(Object o) {
        if (o == this) {
            return true;
        }

        if (o instanceof Coal) {
            return true;
        }

        return false;
    }

    public String toString() {
        return "Coal";
    }
}
