package szoftprojlab.resource;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ice.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//


import szoftprojlab.Asteroid;

public class Ice extends Resource {
	@Override
	public void SeeSun(Asteroid asteroid) {
		System.out.println("Ice.SeeSun()");
		System.out.println("Ice destroyed");
		System.out.println("return from Ice.SeeSun()");
	}

	@Override
	public void AddToOwner(ResourceStorage rs) {
		rs.AddResource(ResourceNames.Ice, this);
	}
}
