package szoftprojlab.resource;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ice.java
//  @ Date : 10/03/2021
//  @ Author : 
//
//


import szoftprojlab.Asteroid;
import szoftprojlab.skeleton.ObjectHolder;

public class Ice extends Resource {
	/**
	 * The sun gets close the ice
	 * The ice is destoryed
	 * @param asteroid - the asteroid which holds the ice
	 */
	@Override
	public void SeeSun(Asteroid asteroid) {
		ObjectHolder oh = ObjectHolder.getInstance();
		String objectName = oh.get(this);
		System.out.println(objectName+".SeeSun()");
		asteroid.DestroyResource();
		System.out.println("return from "+objectName+".SeeSun()");
	}

	@Override
	public boolean equals(Object o) {
		if (o == this) {
			return true;
		}

		if (o instanceof Ice) {
			return true;
		}

		return false;
	}
}
