package szoftprojlab.resource;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ice.java
//  @ Date : 10/03/2021
//  @ Author : 
//
//


import szoftprojlab.Asteroid;
import szoftprojlab.Main;

public class Ice extends Resource {

	/**
	 * The sun gets close the ice
	 * The ice is destoryed
	 * @param asteroid - the asteroid which holds the ice
	 */
	@Override
	public void SeeSun(Asteroid asteroid) {
		Main.println("The ice is destroyed");
		asteroid.DestroyResource();
	}

	@Override
	public boolean equals(Object o) {
		if (o == this) {
			return true;
		}

		if (o instanceof Ice) {
			return true;
		}

		return false;
	}

	/**
	 * Returns the resource part of the image
	 * @return  resource name used in the images
	 */
	@Override
	public String GetImagePart() { return "ice"; }

	public String toString() {
		return "Ice";
	}
}
