package szoftprojlab.resource;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Iron.java
//  @ Date : 10/03/2021
//  @ Author : 
//
//


public class Iron extends Resource {
    @Override
    public boolean equals(Object o) {
        if (o == this) {
            return true;
        }

        if (o instanceof Iron) {
            return true;
        }

        return false;
    }

    /**
     * Returns the resource part of the image
     *
     * @return resource name used in the images
     */
    @Override
    public String GetImagePart() {
        return "iron";
    }


    public String toString() {
        return "Iron";
    }
}
