package szoftprojlab.resource;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ReourceStorage.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//




public interface ResourceStorage {
	public void AddResource(ResourceNames name, Resource resource);
}
