package szoftprojlab.resource;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Resource.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//


import szoftprojlab.Asteroid;

public abstract class Resource {
    public void SeeSun(Asteroid asteroid) {
    }

    @Override
    public abstract boolean equals(Object o);
}
