package szoftprojlab.resource;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Resource.java
//  @ Date : 10/03/2021
//  @ Author : 
//
//


import szoftprojlab.Asteroid;
import szoftprojlab.skeleton.ObjectHolder;

public abstract class Resource {
    /**
     * The Sun gets close to the resource
     * @param asteroid - the asteroid which holds the resource
     */
    public void SeeSun(Asteroid asteroid) {
        ObjectHolder oh = ObjectHolder.getInstance();
        String objectName = oh.get(this);
        System.out.println(objectName+".SeeSun()");
        System.out.println("return from "+objectName+".SeeSun()");
    }

    @Override
    public abstract boolean equals(Object o);
}
