package szoftprojlab.resource;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Uranium.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//


import szoftprojlab.Asteroid;

public class Uranium implements Resource {
	public void SeeSun(Asteroid asteroid) {
	}
	
	public void AddToOwner(ResourceStorage rs) {
	}
}
