package szoftprojlab.entity;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Entity.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//


import szoftprojlab.Asteroid;
import szoftprojlab.Steppable;
import szoftprojlab.TeleportGate;

public abstract class Entity implements Steppable {
	private Asteroid asteroid;

	public Asteroid GetAsteroid() {
		return asteroid;
	}

	public void SunStorm() {
	}
	
	public void Explode() {
	}
	
	public void MoveTo(Asteroid asteroid) {
	}
	
	protected void Drill() {
	}
	
	protected void Teleport(TeleportGate gate) {
	}
	
	protected void AddResourcesToComparator() {
	}
}
