package szoftprojlab.entity;

//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Robot.java
//  @ Date : 02/03/2021
//  @ Author : 
//
//


import szoftprojlab.Asteroid;
import szoftprojlab.Blueprint;
import szoftprojlab.resource.*;

import java.util.List;

public class Robot extends Entity {
	private static Blueprint robotBlueprint = new Blueprint(new Iron(), new Coal(), new Uranium());

	public Robot() {
		System.out.println("Robot - create");
		System.out.println("return from Robot - create");
	}

	public void Step() {
	}
	
	public void Explode() {
		System.out.println("Robot.Explode()");
		Asteroid newAsteroid = asteroid.GetRandomNeighbor();
		asteroid.Remove(this);
		if (newAsteroid != null)
			newAsteroid.Accept(this);

		System.out.println("return from Robot.Explode()");
	}
	
	public void Robot(Asteroid asteroid) {
	}

	public List<Resource> CanCraft(List<Resource> rs) {
		System.out.println("Robot.CanCraft()");
		List<Resource> list = robotBlueprint.IsCraftable(rs);
		System.out.println("return from Robot.CanCraft()");
		return list;
	}
}
